### ISSUE TITLE
关于缓存数据一致性问题

### ISSUE THREAD

**Issue by Johnson0125** [timebusker/spring-boot#10]
首先感谢您的spring-boot项目，我在学习到ehcache这一章的时候，发现我先调用带有@Cacheable的list查询出来结果后，然后调用带有CachePut的更新方法，更新成功，刷新list查询，发现输出的还是旧数据，请问这个一致性，有没有啥好滴办法，谢谢

**Comment by timebusker** [comment]
你需要先确认一下，你 put到缓存内的KEY值是不是一致的，读取缓存的时候，是完全根据KEY值获取的。

在实践中，我有测试了多个用例，你理理源码看看。
