### ISSUE TITLE
diskPersistent ="true" 的场合，在VM重启的场合，如何将缓存数据写到Disk？

### ISSUE THREAD

**Issue by wurangbo** [timebusker/spring-boot#9]

**Comment by timebusker** [comment]
<diskStore path="java.io.tmpdir/ehcache-temp" />设置缓存硬盘存储地址
overflowToDisk：true表示当内存缓存的对象数目达到了maxElementsInMemory界限后，会把溢出的对象写到硬盘缓存中。注意：如果缓存的对象要写入到硬盘中的话，则该对象必须实现了Serializable接口；
diskPersistent：是否缓存虚拟机重启期数据；

**Comment by wurangbo** [comment]
我看有人说要通过shutdown hook，但是不知道spring boot中如何配置 shutdownlistener。
